# Generated by Django 5.2 on 2025-04-23 10:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=20)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('qr_code_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(max_length=50)),
                ('patient_type', models.CharField(choices=[('OPD', 'Outpatient'), ('IPD', 'Inpatient'), ('Emergency', 'Emergency')], max_length=50)),
                ('source_of_enquiry', models.CharField(choices=[('Website', 'Website'), ('Phone Call', 'Phone Call'), ('Walk-in', 'Walk-in'), ('Referral', 'Referral')], max_length=100)),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True)),
                ('interest', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('waiting', 'Waiting for Decision')], default='waiting', max_length=20, verbose_name='Interest')),
                ('enquiry_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryAdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.TextField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='EnquiryManager.enquiry')),
            ],
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.enquiryfor'),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.doctor')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.enquiry')),
                ('surgery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.surgerytype')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_surgery_scheduled', models.BooleanField(default=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('appointment_date', models.DateField()),
                ('consultation_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='consultation_qrcodes/')),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.consultationtype')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.doctor')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='EnquiryManager.enquiry')),
                ('surgery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnquiryManager.surgerytype')),
            ],
        ),
    ]
