# Generated by Django 5.2 on 2025-04-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown')], max_length=20)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='State',
            new_name='CityEntry',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='EnquiryManager.enquiry'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_surgery_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultation_qrcodes/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='interest',
            field=models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('waiting', 'Waiting for Decision')], default='waiting', max_length=20, verbose_name='Interest'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='qr_code_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgery',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.enquiry'),
        ),
        migrations.AddField(
            model_name='surgery',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EnquiryAdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.TextField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='EnquiryManager.enquiry')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnquiryManager.surgerytype'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EnquiryManager.surgerytype'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
