# Generated by Django 5.2 on 2025-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiryfor',
            options={'verbose_name': 'Enquiry For', 'verbose_name_plural': 'Enquiry For'},
        ),
        migrations.AlterField(
            model_name='enquiryfor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
