# Generated by Django 5.2 on 2025-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquiryManager', '0002_dynamicfield_pincodeentry_stateentry_surgerytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
